language: cpp

compiler:
  - gcc
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

notifications:
  email: false

script:
  - scons
  - ./Test.out