
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

# environment variables
environment:
  PYTHON: "C:\\Python27"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build: off

# scripts to run before build
before_build:
  - python --version
  - scons --version

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - scons

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - Test.exe